### ISSUE TITLE
`let x = x` inconsistently treats `x` as defined

### ISSUE THREAD

**Issue by apt1002** [ursalang/ursa#3]
```ursa
> let y = x; y
undefined symbol x
> let x = x; x
null
```

**Comment by rrthomas** [comment]
Closing. This is deliberate: the scope of an identifier includes its initializer. This allows recursive functions. The second example will be made illegal eventually by type checking.

**Comment by rrthomas** [comment]
I have improved the situation (will be in 0.0.15) by detecting uninitialized symbols at run-time.
