### ISSUE TITLE
Assertion error in compiler

### ISSUE THREAD

**Issue by apt1002** [ursalang/ursa#4]
```ursa
fn fac(x) {
  if x == 0 {1} else {x * fac(x - 1)}
}
fac(6)
```

**Comment by apt1002** [comment]
```ursa
fn() {
    x = 7
    x
}
```

However, without the enclosing function we get "undefined symbol x" instead.

**Comment by rrthomas** [comment]
The first example is no longer syntactically valid, but the second still gives the error.
